version: '3.7'

services:
  django_gunicorn:
    container_name: gunicorn_container
    volumes:
      - static:/app/productionfiles/
    build:
      context: .
    expose:
      - "8000"
    networks:
      blogs:

  nginx:
    container_name: nginx_container
    build: ./nginx
    volumes:
      - static:/app/productionfiles/
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn
    networks:
      blogs:

  locust:
    container_name: locust_container
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./locust:/locust
      - ./stats:/stats
    command: 
      -f "/locust/locustfile.py" -H "http://192.168.169.44" -u 1000 -r 10 -t 30s --autostart --csv "/stats/" --autoquit 2 --only-summary
    depends_on:
      - nginx
volumes:
  static:
  locust_file:

networks:
  blogs:


