version: '3.7'

services:
  django_gunicorn:
    volumes:
      - static:/app/productionfiles/
    build:
      context: .
    expose:
      - "8000"
    networks:
      blogs:

  nginx:
    build: ./nginx
    volumes:
      - static:/app/productionfiles/
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn
    networks:
      blogs:
      
volumes:
  static:

networks:
  blogs:


