# Generated by Django 5.0.1 on 2024-01-30 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_blogs_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='date',
            field=models.DateField(default=datetime.date(2024, 1, 30)),
        ),
    ]
