# Generated by Django 5.0.1 on 2024-01-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_blogs_likes_alter_blogs_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='verified_writer',
            name='profile_picture',
            field=models.ImageField(default='', upload_to='users/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='writer',
            name='profile_picture',
            field=models.ImageField(default='', upload_to='users/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
