# Generated by Django 5.0.1 on 2024-01-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_verified_writer_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='profile_picture',
            field=models.ImageField(default='', upload_to='users/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
